name: Github Actions 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@3
      - name: Use Node.hs==js version 20
        uses: actions/setup-node@3
        with:
          node-version: '20'
      - run: npm install 
      - run: npm run build --prefix client

